const ALL_POKEMONS = "ALL_POKEMONS";
const ALL_TYPES = "ALL_TYPES";

const FILTER_TYPES = "FILTER_TYPES";
const FILTER_ORIGEN = "FILTER_ORIGEN";
const ORDEN = "ORDEN";
const ORDEN_ALFA = "ORDEN_ALFA";
const ORDEN_ATTACK = "ORDEN_ATTACK";

export {
  ALL_POKEMONS,
  ALL_TYPES,
  FILTER_TYPES,
  FILTER_ORIGEN,
  ORDEN,
  ORDEN_ALFA,
  ORDEN_ATTACK,
};
